_wandb:
    value:
        cli_version: 0.25.0
        e:
            uql8fs79j0o1te9tb531arlfkb2d0761:
                apple:
                    ecpuCores: 4
                    gpuCores: 10
                    memoryGb: 16
                    name: Apple M3
                    pcpuCores: 4
                    ramTotalBytes: "17179869184"
                    swapTotalBytes: "6442450944"
                codePath: assignment02.ipynb
                codePathLocal: assignment02.ipynb
                cpu_count: 8
                cpu_count_logical: 8
                disk:
                    /:
                        total: "994662584320"
                        used: "334609162240"
                email: c.tingkuo216@gmail.com
                executable: /Users/zhenting/miniconda3/envs/7374_LLM/bin/python3.11
                git:
                    commit: 72bd68bf5ae2ba12908c212b04769cb1f2fe521e
                    remote: https://github.com/ctkuo2438/CSYE7374.git
                host: Mac.localdomain
                memory:
                    total: "17179869184"
                os: macOS-15.1-arm64-arm-64bit
                program: assignment02.ipynb
                python: CPython 3.11.14
                root: /Users/zhenting/7374_LLM/Assignment_02
                startedAt: "2026-02-18T00:42:34.569722Z"
                writerId: uql8fs79j0o1te9tb531arlfkb2d0761
        m: []
        python_version: 3.11.14
        t:
            "1":
                - 1
            "2":
                - 1
            "3":
                - 1
                - 2
                - 13
                - 16
                - 61
            "4": 3.11.14
            "5": 0.25.0
            "8":
                - 1
            "12": 0.25.0
            "13": darwin-arm64
batch_size:
    value: 16
block_size:
    value: 128
lr:
    value: 0.0003
max_steps:
    value: 2000
n_embd:
    value: 256
n_head:
    value: 4
n_layer:
    value: 2
vocab_size:
    value: 50257
